# ここに設定した名前がActions上に表示される
name: pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  pytest:
    name: Run tests with pytest
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest
    # 複数の Python のバージョンでテストするために `strategy.matrix` を設定する
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      # リポジトリをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v2
      #ls
      #cd 
      - name: cd 
        run: |
          ls
          pwd
          cd Currency
      # pytest を実行する
      - name: Run Tests
        run: |
          docker-compose up -d --build
          docker-compose exec -T test-app poetry run pytest tests/test.py
      - name: Upload coverage to Codecov
        # 上記のstepsが全て完了した場合にcodecovへupload
        # 今回はpublic repositoryのためKEYは不要だが、privateなら必要なので注意
        if: ${{ matrix.python-version==3.8 }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true


